<a href="https://colab.research.google.com/github/Vaishu03/ML/blob/main/Products_Review_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Import Library

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import matplotlib.pyplot as plt

In [4]:
import seaborn as sns

## Import Dataset

In [5]:
df = pd.read_csv('https://raw.githubusercontent.com/NadimKawwa/WomeneCommerce/master/Womens%20Clothing%20E-Commerce%20Reviews.csv',index_col=0)

In [6]:
df.head()

Clothing ID  Age                    Title  \
0          767   33                      NaN   
1         1080   34                      NaN   
2         1077   60  Some major design flaws   
3         1049   50         My favorite buy!   
4          847   47         Flattering shirt   

                                         Review Text  Rating  Recommended IND  \
0  Absolutely wonderful - silky and sexy and comf...       4                1   
1  Love this dress!  it's sooo pretty.  i happene...       5                1   
2  I had such high hopes for this dress and reall...       3                0   
3  I love, love, love this jumpsuit. it's fun, fl...       5                1   
4  This shirt is very flattering to all due to th...       5                1   

   Positive Feedback Count   Division Name Department Name Class Name  
0                        0       Initmates        Intimate  Intimates  
1                        4         General         Dresses    Dresses  
2                        0         General         Dresses    Dresses  
3                        0  General Petite         Bottoms      Pants  
4                        6         General            Tops    Blouses

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 23486 entries, 0 to 23485
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   Clothing ID              23486 non-null  int64 
 1   Age                      23486 non-null  int64 
 2   Title                    19676 non-null  object
 3   Review Text              22641 non-null  object
 4   Rating                   23486 non-null  int64 
 5   Recommended IND          23486 non-null  int64 
 6   Positive Feedback Count  23486 non-null  int64 
 7   Division Name            23472 non-null  object
 8   Department Name          23472 non-null  object
 9   Class Name               23472 non-null  object
dtypes: int64(5), object(5)
memory usage: 2.0+ MB


In [8]:
df.shape

(23486, 10)

## Missing values

In [9]:
df.isna().sum()

Clothing ID                   0
Age                           0
Title                      3810
Review Text                 845
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

In [10]:
df[df["Review Text"]==""] = np.NaN

In [11]:
df['Review Text'].fillna('No Review',inplace=True)

In [12]:
df.isna().sum()

Clothing ID                   0
Age                           0
Title                      3810
Review Text                   0
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

In [13]:
df['Review Text']

0        Absolutely wonderful - silky and sexy and comf...
1        Love this dress!  it's sooo pretty.  i happene...
2        I had such high hopes for this dress and reall...
3        I love, love, love this jumpsuit. it's fun, fl...
4        This shirt is very flattering to all due to th...
                               ...                        
23481    I was very happy to snag this dress at such a ...
23482    It reminds me of maternity clothes. soft, stre...
23483    This fit well, but the top was very see throug...
23484    I bought this dress for a wedding i have this ...
23485    This dress in a lovely platinum is feminine an...
Name: Review Text, Length: 23486, dtype: object

## Define Target and Features

In [14]:
df.columns

Index(['Clothing ID', 'Age', 'Title', 'Review Text', 'Rating',
       'Recommended IND', 'Positive Feedback Count', 'Division Name',
       'Department Name', 'Class Name'],
      dtype='object')

In [15]:
X = df['Review Text']

In [16]:
y = df['Rating']

In [17]:
df['Rating'].value_counts()

5.0    13131
4.0     5077
3.0     2871
2.0     1565
1.0      842
Name: Rating, dtype: int64

## Train Test Split

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=10)

In [20]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((16440,), (7046,), (16440,), (7046,))

## Get Feature Text Conversion to tokens

In [21]:
from sklearn.feature_extraction.text import CountVectorizer

In [22]:
cv = CountVectorizer(lowercase=True,analyzer = 'word',ngram_range=(2,3),stop_words='english',max_features=5000)

In [23]:
X_train = cv.fit_transform(X_train)

In [24]:
cv.get_feature_names_out()

array(['10 12', '10 bought', '10 fit', ..., 'years old', 'yellow color',
       'yoga pants'], dtype=object)

In [25]:
X_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [26]:
X_test = cv.fit_transform(X_test)

In [27]:
cv.get_feature_names_out()

array(['0p fits', '10 10', '10 12', ..., 'years ago', 'years come',
       'yoga pants'], dtype=object)

In [28]:
X_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

## Get Model Train

In [29]:
from sklearn.naive_bayes import MultinomialNB

In [30]:
model = MultinomialNB()

In [31]:
model.fit(X_train,y_train)

MultinomialNB()

## Get Model Prediction

In [32]:
y_pred = model.predict(X_test)

In [33]:
y_pred.shape

(7046,)

In [34]:
y_pred

array([5., 4., 3., ..., 1., 5., 5.])

## Get Probability of each predicted class

In [35]:
model.predict_proba(X_test)

array([[0.08337456, 0.16770366, 0.03255203, 0.12528584, 0.59108392],
       [0.00525763, 0.02141505, 0.2153847 , 0.63404505, 0.12389757],
       [0.01960753, 0.03859512, 0.78151458, 0.03156186, 0.12872091],
       ...,
       [0.55649776, 0.15983099, 0.14742699, 0.09495979, 0.04128446],
       [0.03431049, 0.04267549, 0.05047076, 0.15969746, 0.7128458 ],
       [0.02997685, 0.02937781, 0.00498543, 0.38369065, 0.55196927]])

## Get Model Evaluation

In [36]:
from sklearn.metrics import confusion_matrix,classification_report

In [37]:
print(confusion_matrix(y_test,y_pred))

[[  21   20   35   51  158]
 [  49   42   82   88  233]
 [ 107   86  119  153  348]
 [ 182  120  220  294  692]
 [ 453  300  491  716 1986]]


In [38]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         1.0       0.03      0.07      0.04       285
         2.0       0.07      0.09      0.08       494
         3.0       0.13      0.15      0.14       813
         4.0       0.23      0.19      0.21      1508
         5.0       0.58      0.50      0.54      3946

    accuracy                           0.35      7046
   macro avg       0.21      0.20      0.20      7046
weighted avg       0.39      0.35      0.37      7046



## Categorise Ratings as Poor(0) and Good(1)

In [39]:
df['Rating'].value_counts()

5.0    13131
4.0     5077
3.0     2871
2.0     1565
1.0      842
Name: Rating, dtype: int64

***Re rating as 1,2,3 as 0 and 4,5 as 1***

In [40]:
df.replace({'Rating':{1:0,2:0,3:0,4:1,5:1}},inplace=True)

In [41]:
y = df['Rating']

In [42]:
X = df['Review Text']

## Train Test Split

In [43]:
from sklearn.model_selection import train_test_split

In [44]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=10)

In [45]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((16440,), (7046,), (16440,), (7046,))

## Get Feature text conversions to tokens

In [47]:
cv = CountVectorizer(lowercase=True,analyzer = 'word',ngram_range=(2,3),stop_words='english',max_features=5000)

In [48]:
X_train = cv.fit_transform(X_train)

In [49]:
X_test = cv.fit_transform(X_test)

## Get Model Re-train

In [50]:
model.fit(X_train,y_train)

MultinomialNB()

## Get Model Prediction

In [51]:
y_pred = model.predict(X_test)

In [52]:
y_pred.shape

(7046,)

In [53]:
y_pred

array([1., 1., 0., ..., 0., 1., 1.])

## Get Model Evaluation

In [54]:
from sklearn.metrics import confusion_matrix,classification_report

In [55]:
print(confusion_matrix(y_test,y_pred))

[[ 438 1154]
 [1240 4214]]


In [56]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.26      0.28      0.27      1592
         1.0       0.79      0.77      0.78      5454

    accuracy                           0.66      7046
   macro avg       0.52      0.52      0.52      7046
weighted avg       0.67      0.66      0.66      7046

